### ISSUE TITLE
panic when targeting resource in JSON config

### ISSUE THREAD

**Issue by matschaffer-roblox** [hashicorp/terraform-ls#1157]
### Server Version
```
0.30.1
```

### Terraform Version

```
v1.2.6
```

### Client Version

```
VScode Version: 1.74.3 (Universal)
```

### Terraform Configuration Files

Terraform is all JSON generated by cdktf. The JSON is 800 lines which would be difficult to redact and post here.

### Log Output

```
Launching language server: /Users/mat.schaffer/.vscode/extensions/hashicorp.terraform-2.25.2-darwin-arm64/bin/terraform-ls serve
2023/01/30 17:18:21 serve_command.go:101: Starting terraform-ls 0.30.1
2023/01/30 17:18:21 service.go:99: Preparing new session ...
2023/01/30 17:18:21 langserver.go:94: Starting server (pid 4608; concurrency: 5) ...
2023/01/30 17:18:21 opts.go:205: Received request batch of size 1 (qlen=0)
2023/01/30 17:18:21 opts.go:205: Dequeued request batch of length 1 (qlen=0)
2023/01/30 17:18:21 rpc_logger.go:29: Incoming request for "initialize" (ID 0): {"processId":4550,"clientInfo":{"name":"Visual Studio Code","version":"1.74.3"},"locale":"en-us","rootPath":"(one of the cdktf.out stacks)"...
[snip]
2023/01/30 17:18:21 jobs.go:268: JOBS: Dispatching next job "6" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeDecodeReferenceTargets" for {"file://(one of the cdktf.out stacks)"}
2023/01/30 17:18:21 jobs.go:246: retrying on obj is nil
2023/01/30 17:18:21 provider_schema.go:279: PSS: getting provider schema ((one of the cdktf.out stacks), registry.terraform.io/hashicorp/aws, 4.23.0)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102bf6be0]

goroutine 21 [running]:
github.com/hashicorp/hcl-lang/lang.Address.String(...)
	github.com/hashicorp/hcl-lang@v0.0.0-20221130131410-9f07ba77f1d7/lang/address_steps.go:23
github.com/hashicorp/hcl-lang/reference.Targets.Less({0x140036ec000?, 0x2f?, 0x0?}, 0x0?, 0x0?)
	github.com/hashicorp/hcl-lang@v0.0.0-20221130131410-9f07ba77f1d7/reference/targets.go:32 +0x2f0
sort.partition({0x1036e35a0, 0x140036da390}, 0x0, 0x2f, 0x14002bbd448?)
	sort/zsortinterface.go:142 +0xc0
sort.pdqsort({0x1036e35a0, 0x140036da390}, 0x18?, 0x103621480?, 0x14000183a01?)
	sort/zsortinterface.go:114 +0x1ac
sort.Sort({0x1036e35a0, 0x140036da390})
	sort/sort.go:48 +0x60
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).decodeReferenceTargetsForBody(0x103638680?, {0x1036e4320, 0x1400039e000}, 0xb?, 0x14003596b40)
	github.com/hashicorp/hcl-lang@v0.0.0-20221130131410-9f07ba77f1d7/decoder/reference_targets.go:236 +0x1474
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CollectReferenceTargets(0x14000562ea0)
	github.com/hashicorp/hcl-lang@v0.0.0-20221130131410-9f07ba77f1d7/decoder/reference_targets.go:94 +0x168
github.com/hashicorp/terraform-ls/internal/terraform/module.DecodeReferenceTargets({0x1036e3de0, 0x14001350ff0}, 0x140003bc000, {0x1036dfce0?, 0x14000381400}, {0x140000a8857, 0x66})
	github.com/hashicorp/terraform-ls/internal/terraform/module/module_ops.go:509 +0x1d4
github.com/hashicorp/terraform-ls/internal/indexer.(*Indexer).collectReferences.func1({0x1036e3de0, 0x14001350ff0})
	github.com/hashicorp/terraform-ls/internal/indexer/module_calls.go:146 +0x68
github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).eval(0x140003ad9b0, {0x1036e3d38?, 0x140003bc040?})
	github.com/hashicorp/terraform-ls/internal/scheduler/scheduler.go:70 +0xf8
created by github.com/hashicorp/terraform-ls/internal/scheduler.(*Scheduler).Start
	github.com/hashicorp/terraform-ls/internal/scheduler/scheduler.go:48 +0x80
Failure to start terraform-ls. Please check your configuration settings and reload this window
```

### Expected Behavior

No error

### Actual Behavior

Error. Presented like this in vscode when opening the project.

<img width="468" alt="Screen Shot 2023-01-30 at 5 26 42 PM" src="https://user-images.githubusercontent.com/115565899/215635921-db70d7e7-d730-486c-b2fa-89661fab325c.png">

### Steps to Reproduce

The project I'm working on is large and kind of complex. Is there a good way to start the language server and feed it a request in place of vscode to force the failure? If so I can maybe come up with a good minimal reproduction.

**Comment by radeksimko** [comment]
Hi @matschaffer-roblox 
Thanks for the report. `panic` should certainly not be happening and so this is a bug.

I can see it relates to the collection of reference targets, but we'd need a little more detail to understand the root cause. This may be triggered by any addressable block, such as `resource`, `data`, or even `variable` or `locals` entry. The only "good news" is that this is less likely to be triggered by the contents of a block and references generally. So you could try to keep removing resources, data sources, variables etc. to narrow it down to a specific one.

Alternatively, you could PGP-encrypt the JSON config [using my pubkey](https://keybase.io/radeksimko) and share it here, or send it to `radek <at> hashicorp.com`.

**Comment by matschaffer-roblox** [comment]
Thanks @radeksimko - I'll see if I can narrow it down by just removing things from the generated json and restarting vscode between runs.

If there's a way to curl (or something) the language server to get it to read the directory, please let me know.

**Comment by radeksimko** [comment]
FWIW you don't need to restart whole VS Code, you can open the command palette and "Reload window", which should re-activate the extension and relaunch the server.

![Screenshot 2023-01-31 at 17 38 22](https://user-images.githubusercontent.com/287584/215839692-4f9eeb2f-f174-46ea-919e-0838279e534d.png)

**Comment by matschaffer-roblox** [comment]
Ah, awesome. Thanks!

**Comment by matschaffer-roblox** [comment]
So after some manual bisecting, this seems to be a minimal `cdk.tf.json` that will trigger a crash.

```json
{
  "resource": {
    "aws_emr_cluster": {
      "my-cluster": {
        "master_instance_fleet": {
        }
      }
    }
  }
}
```

If you put that in a folder, run `code .` then open that file, you should be able to see the same crash.

**Comment by radeksimko** [comment]
Reproduced, thank you!

I just had to trigger completion involving that resource in another file, e.g.

```hcl
output "test" {
  value = aws_emr_cluster.my-cluster. # HERE
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10092dd2c]

goroutine 204 [running]:
github.com/hashicorp/hcl-lang/lang.Address.String(...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/lang/address_steps.go:23
github.com/hashicorp/hcl-lang/reference.localTargetMatches({_, _}, {{0x1400247f940, 0x3, 0x4}, {0x14000ad9880, 0x1, 0x1}, 0x0, {0x100b696d9, ...}, ...}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/reference/targets.go:89 +0x3cc
github.com/hashicorp/hcl-lang/reference.Targets.MatchWalk({0x140008782c0?, 0x1, 0x140008782c0?}, {0x1013a4360, 0x140032a7c20}, {{0x0, 0x0}, {{0x1013a4e18, 0x1017aa8a8}}, {0x0, ...}, ...}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/reference/targets.go:78 +0x14c
github.com/hashicorp/hcl-lang/reference.Targets.MatchWalk({0x140002a2100?, 0x7, 0x140009c7118?}, {0x1013a4360, 0x140032a7c20}, {{0x0, 0x0}, {{0x1013a4e18, 0x1017aa8a8}}, {0x0, ...}, ...}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/reference/targets.go:84 +0x27c
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).candidatesForTraversalConstraint(0x140008e9710, {0x1013a4360, 0x140032a7c20}, {{0x0, 0x0}, {{0x1013a4e18, _}}, {_, _}, _}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/expression_candidates.go:462 +0x1b8
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).constraintToCandidates(0x140008e9320?, {0x1013a4360, 0x140032a7c20}, {0x1013a3d30?, 0x14002b9b940?}, 0x35?, {{0x1400116407e, 0x7}, {0x2, 0xf, ...}, ...}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/expression_candidates.go:332 +0x66c
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).attrValueCandidatesAtPos(0x140008e9710, {0x1013a4360, 0x140032a7c20}, 0x14000bac000, 0x140008e9830, {{0x1400116407e, 0x7}, {0x2, 0xf, 0xf}, ...}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/expression_candidates.go:52 +0x408
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).candidatesAtPos(0x1012f57a0?, {0x1013a4360, 0x140032a7c20}, 0x140005c2420, {{0x1400116407e, 0x7}, {0x2, 0xf, 0xf}, {0x4, ...}}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/candidates.go:63 +0x93c
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).candidatesAtPos(0x1012f58c0?, {0x1013a4360, 0x140032a7c20}, 0x140005c24d0, {{0x1400116407e, 0x7}, {0x2, 0xf, 0xf}, {0x4, ...}}, ...)
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/candidates.go:145 +0x1150
github.com/hashicorp/hcl-lang/decoder.(*PathDecoder).CandidatesAtPos(0x140008e9710, {0x1013a4360, 0x140032a7c20}, {0x1400116407e, 0x7}, {0x1400017aaf0?, 0x1010000?, 0x1010101?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/hcl-lang/decoder/candidates.go:41 +0x1f0
github.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).TextDocumentComplete(0x140001d4c60, {0x1013a4360, 0x140032a7c20}, {{0x4000000000000000, {0x10171db70, 0x1}}, {{{0x14003136db0, 0x25}}, {0x2, 0x25}}, ...})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform-ls/internal/langserver/handlers/complete.go:43 +0x2bc
reflect.Value.call({0x1012f09a0?, 0x14003396320?, 0x140001c34e8?}, {0x100b6747e, 0x4}, {0x140032a7cb0, 0x2, 0x100b4b568?})
	/Users/radeksimko/.goenv/versions/1.19.3/src/reflect/value.go:584 +0x688
reflect.Value.Call({0x1012f09a0?, 0x14003396320?, 0x1013358a0?}, {0x140032a7cb0?, 0x14003396320?, 0x14000bf1e20?})
	/Users/radeksimko/.goenv/versions/1.19.3/src/reflect/value.go:368 +0x90
github.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({0x1013a4360?, 0x140032a7c20?}, 0x101b0c108?)
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/handler/handler.go:231 +0x12c
github.com/hashicorp/terraform-ls/internal/langserver/handlers.handle({0x1013a4360, 0x140032a7c20}, 0x1012eaae0?, {0x1012f09a0?, 0x14003396320?})
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:578 +0x54
github.com/hashicorp/terraform-ls/internal/langserver/handlers.(*service).Assigner.func10({0x1013a4360?, 0x140032a7b90?}, 0x2?)
	/Users/radeksimko/gopath/src/github.com/hashicorp/terraform-ls/internal/langserver/handlers/service.go:218 +0x138
reflect.Value.call({0x101304a40?, 0x140003053b0?, 0x1400048fd58?}, {0x100b6747e, 0x4}, {0x140032a7bc0, 0x2, 0x100b73c51?})
	/Users/radeksimko/.goenv/versions/1.19.3/src/reflect/value.go:584 +0x688
reflect.Value.Call({0x101304a40?, 0x140003053b0?, 0x140032a7b90?}, {0x140032a7bc0?, 0x10133da00?, 0x14000962000?})
	/Users/radeksimko/.goenv/versions/1.19.3/src/reflect/value.go:368 +0x90
github.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func8({0x1013a4360?, 0x140032a7b90?}, 0x140032a7b90?)
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/handler/handler.go:231 +0x12c
github.com/creachadair/jrpc2.(*Server).invoke(0x140002bb520, {0x1013a42b8?, 0x14000962040?}, 0x1400036e060, 0x14000962000)
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/server.go:384 +0xf4
github.com/creachadair/jrpc2.(*Server).dispatch.func1()
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/server.go:256 +0x168
github.com/creachadair/jrpc2.(*Server).serve.func1()
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/server.go:178 +0x58
created by github.com/creachadair/jrpc2.(*Server).serve
	/Users/radeksimko/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.43.0/server.go:176 +0x24
```

**Comment by matschaffer-roblox** [comment]
Nice! I suspect you can open the json file to trigger the panic as well. In the minimal repo I don't have any HCL at all, just that one file.

There is some HCL in the larger repo, but I don't think we target any of the JSON resources from HCL. We mostly work in cdktf anyway, so typescript handles references. But it'd be nice to figure out the panic to avoid the popup any time I reopen vscode.

Thanks in advance for anything you're able to do about it. If I can provide anything else just let me know.

**Comment by matschaffer-roblox** [comment]
thanks @dbanck !
