### ISSUE TITLE
Language server is failing to start.

### ISSUE THREAD

**Issue by sunnynazar** [hashicorp/terraform-ls#160]
I am getting below error while trying to install the latest version of this extension.
----------------------------------------------------------------------------------------
Launching language server: c:\Users\SunnyNazar\.vscode\extensions\hashicorp.terraform-2.0.1/lsp/terraform-ls serve
[Error - 9:00:32 PM] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)
	at c:\Users\SunnyNazar\.vscode\extensions\hashicorp.terraform-2.0.1\node_modules\vscode-languageclient\lib\main.js:354:40

-----------------------------------------------------------------------------------------

Could you please check.

**Comment by radeksimko** [comment]
I don't run on Windows myself, but the error code suggests this may happen when a file is overwritten when being used by the system. This would likely never happen if the server was installed automatically on VSCode launch, as the server never starts before it's installed/upgraded, but this could happen on manual enabling/disabling I assume and we should probably address that.

Either way I believe this something to be addressed on the VSCode side, so I'm going to transfer the issue there.
