### ISSUE TITLE
command 'terraform-ls.rootmodules' already exists

### ISSUE THREAD

**Issue by Brike70** [hashicorp/terraform-ls#297]
### Server Version

```
0.9.0
```

### Terraform Version

```
Terraform v0.13.5
```

### Client Version

```
hashicorp.terraform-2.2.3
```

### Terraform Configuration Files

```
any config
```

### Log Output

```
Couldn't start client Language Server: file:///c%3A/Users/me/Documents/project/
command 'terraform-ls.rootmodules' already exists
```

### Expected Behaviour

Just works

### Actual Behaviour

```
Couldn't start client Language Server: file:///c%3A/Users/me/Documents/project/
command 'terraform-ls.rootmodules' already exists
```

### Steps to Reproduce

- So on Windows 10 in VSCode, install the following extension:

```
Name: HashiCorp Terraform
Id: hashicorp.terraform
Description: Syntax highlighting and autocompletion for Terraform
Version: 2.2.3
Publisher: HashiCorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform
```

- Make sure the language server is installed (currently does this automatically for me).

- Then open a .tf file, which will cause the errors to show.

- Manually reverting back to 0.8.0 of the language server resolves this issue, but wanted to flag it up.

Thanks in advance,

Brike.

**Comment by fboula** [comment]
Same error at VSCode start on Ubuntu 18.04

### Log Output

```
Error: command 'terraform-ls.rootmodules' already exists
	at _.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:698:448)
	at Object.registerCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:994:336)
	at ExecuteCommandFeature.register (/home/me/.vscode/extensions/hashicorp.terraform-2.2.3/node_modules/vscode-languageclient/lib/client.js:1650:53)
	at ExecuteCommandFeature.initialize (/home/me/.vscode/extensions/hashicorp.terraform-2.2.3/node_modules/vscode-languageclient/lib/client.js:1630:14)
	at LanguageClient.initializeFeatures (/home/me/.vscode/extensions/hashicorp.terraform-2.2.3/node_modules/vscode-languageclient/lib/client.js:2462:21)
	at /home/me/.vscode/extensions/hashicorp.terraform-2.2.3/node_modules/vscode-languageclient/lib/client.js:2147:18
```
## Environment

```bash
code --version
1.51.0
fcac248b077b55bae4ba5bab613fd6e9156c2f0c
x64

code --list-extensions --show-versions 
hashicorp.terraform@2.2.3
```

**Comment by sethbacon** [comment]
Also received this error on Windows 10 after being prompted to update to version 0.9 on opening VSCode.
